// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptlpbfdzuhsguhhjsuuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0bHBiZmR6dWhzZ3VoaGpzdXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzcxNjcsImV4cCI6MjA2ODU1MzE2N30.XsIU7XawltmDJkEem42ZPvc4ErmnVPkR6n38NsdB_fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});